module.exports = {
    DEFAULT_LIST_MAX_RECORDS_SIZE: 500,
    RESPONSE_ERROR_STATUS_NOT_AUTHENTICATED: 401,
    RESPONSE_ERROR_STATUS_NOT_AUTHORIZED: 403,
    RESPONSE_ERROR_STATUS_NOT_FOUND: 404,
    RESPONSE_ERROR_STATUS_INVALID_INPUT: 422,
    RESPONSE_ERROR_STATUS_BAD_REQUEST: 400,
    RESPONSE_ERROR_STATUS_INTERNAL_SERVER_ERROR: 500,
}